// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrialUsersMediator.Persistence;

#nullable disable

namespace TrialUsersMediator.Migrations
{
    [DbContext(typeof(TrialUsersDbContext))]
    [Migration("20230616115817_AddTrialUsers")]
    partial class AddTrialUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("TrialUsersMediator.Persistence.TrialUser+Entity", b =>
                {
                    b.Property<long>("Identifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identifier", "Platform");

                    b.ToTable("TrialUsers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
