// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrialUsersMediator;

#nullable disable

namespace TrialUsersMediator.Migrations
{
    [DbContext(typeof(TrialUsersDbContext))]
    partial class TrialUsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("TrialUsersMediator.TrialUser+Entity", b =>
                {
                    b.Property<long>("Identifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identifier", "Platform");

                    b.ToTable("TrialUsers", (string)null);
                });

            modelBuilder.Entity("TrialUsersMediator.TrialUser+Info+Telegram+Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuthenticationDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrialUsers_Info_Telegram", (string)null);
                });

            modelBuilder.Entity("TrialUsersMediator.TrialUser+Quota<Node.Tasks.Models.TaskAction>+Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrialUserIdentifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrialUserPlatform")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_entries")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Entries");

                    b.HasKey("Id");

                    b.HasIndex("TrialUserIdentifier", "TrialUserPlatform")
                        .IsUnique();

                    b.ToTable("TrialUsers_Quota", (string)null);
                });

            modelBuilder.Entity("TrialUsersMediator.TrialUser+Entity", b =>
                {
                    b.OwnsOne("TrialUsersMediator.TrialUser+Entity.Info_#TrialUsersMediator.TrialUser+Info+Entity", "Info_", b1 =>
                        {
                            b1.Property<long>("TrialUserIdentifier")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TrialUserPlatform")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("TelegramInfoId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("TrialUserIdentifier", "TrialUserPlatform");

                            b1.HasIndex("TelegramInfoId")
                                .IsUnique();

                            b1.ToTable("TrialUsers_Info", (string)null);

                            b1.HasOne("TrialUsersMediator.TrialUser+Info+Telegram+Entity", "Telegram")
                                .WithOne()
                                .HasForeignKey("TrialUsersMediator.TrialUser+Entity.Info_#TrialUsersMediator.TrialUser+Entity.Info_#TrialUsersMediator.TrialUser+Info+Entity", "TelegramInfoId");

                            b1.WithOwner("TrialUser")
                                .HasForeignKey("TrialUserIdentifier", "TrialUserPlatform");

                            b1.Navigation("Telegram");

                            b1.Navigation("TrialUser");
                        });

                    b.Navigation("Info_")
                        .IsRequired();
                });

            modelBuilder.Entity("TrialUsersMediator.TrialUser+Quota<Node.Tasks.Models.TaskAction>+Entity", b =>
                {
                    b.HasOne("TrialUsersMediator.TrialUser+Entity", "TrialUser")
                        .WithOne("Quota_")
                        .HasForeignKey("TrialUsersMediator.TrialUser+Quota<Node.Tasks.Models.TaskAction>+Entity", "TrialUserIdentifier", "TrialUserPlatform")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrialUser");
                });

            modelBuilder.Entity("TrialUsersMediator.TrialUser+Entity", b =>
                {
                    b.Navigation("Quota_")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
